/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DevBoardRouteImport } from './routes/dev/board'
import { Route as DevNetworkRouteImport } from './routes/dev/network'
import { Route as GameGameIdRouteImport } from './routes/game/$gameId'
import { Route as JoinIndexRouteImport } from './routes/join/index'
import { Route as JoinRoomIdRouteImport } from './routes/join/$roomId'
import { Route as LobbyLobbyIdRouteImport } from './routes/lobby/$lobbyId'
import { Route as LocalGameIdRouteImport } from './routes/local/$gameId'
import { Route as LocalNewRouteImport } from './routes/local/new'
import { Route as OnlineCreateRouteImport } from './routes/online/create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBoardRoute = DevBoardRouteImport.update({
  id: '/dev/board',
  path: '/dev/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNetworkRoute = DevNetworkRouteImport.update({
  id: '/dev/network',
  path: '/dev/network',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomIdRoute = JoinRoomIdRouteImport.update({
  id: '/join/$roomId',
  path: '/join/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyLobbyIdRoute = LobbyLobbyIdRouteImport.update({
  id: '/lobby/$lobbyId',
  path: '/lobby/$lobbyId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalGameIdRoute = LocalGameIdRouteImport.update({
  id: '/local/$gameId',
  path: '/local/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalNewRoute = LocalNewRouteImport.update({
  id: '/local/new',
  path: '/local/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineCreateRoute = OnlineCreateRouteImport.update({
  id: '/online/create',
  path: '/online/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
  '/online/create': typeof OnlineCreateRoute
  '/join/': typeof JoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
  '/online/create': typeof OnlineCreateRoute
  '/join': typeof JoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/join/$roomId': typeof JoinRoomIdRoute
  '/lobby/$lobbyId': typeof LobbyLobbyIdRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
  '/online/create': typeof OnlineCreateRoute
  '/join/': typeof JoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/game/$gameId'
    | '/join/$roomId'
    | '/lobby/$lobbyId'
    | '/local/$gameId'
    | '/local/new'
    | '/online/create'
    | '/join/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/game/$gameId'
    | '/join/$roomId'
    | '/lobby/$lobbyId'
    | '/local/$gameId'
    | '/local/new'
    | '/online/create'
    | '/join'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/game/$gameId'
    | '/join/$roomId'
    | '/lobby/$lobbyId'
    | '/local/$gameId'
    | '/local/new'
    | '/online/create'
    | '/join/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DevBoardRoute: typeof DevBoardRoute
  DevNetworkRoute: typeof DevNetworkRoute
  GameGameIdRoute: typeof GameGameIdRoute
  JoinRoomIdRoute: typeof JoinRoomIdRoute
  LobbyLobbyIdRoute: typeof LobbyLobbyIdRoute
  LocalGameIdRoute: typeof LocalGameIdRoute
  LocalNewRoute: typeof LocalNewRoute
  OnlineCreateRoute: typeof OnlineCreateRoute
  JoinIndexRoute: typeof JoinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/board': {
      id: '/dev/board'
      path: '/dev/board'
      fullPath: '/dev/board'
      preLoaderRoute: typeof DevBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/network': {
      id: '/dev/network'
      path: '/dev/network'
      fullPath: '/dev/network'
      preLoaderRoute: typeof DevNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$roomId': {
      id: '/join/$roomId'
      path: '/join/$roomId'
      fullPath: '/join/$roomId'
      preLoaderRoute: typeof JoinRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$lobbyId': {
      id: '/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof LobbyLobbyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$gameId': {
      id: '/local/$gameId'
      path: '/local/$gameId'
      fullPath: '/local/$gameId'
      preLoaderRoute: typeof LocalGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/new': {
      id: '/local/new'
      path: '/local/new'
      fullPath: '/local/new'
      preLoaderRoute: typeof LocalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online/create': {
      id: '/online/create'
      path: '/online/create'
      fullPath: '/online/create'
      preLoaderRoute: typeof OnlineCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DevBoardRoute: DevBoardRoute,
  DevNetworkRoute: DevNetworkRoute,
  GameGameIdRoute: GameGameIdRoute,
  JoinRoomIdRoute: JoinRoomIdRoute,
  LobbyLobbyIdRoute: LobbyLobbyIdRoute,
  LocalGameIdRoute: LocalGameIdRoute,
  LocalNewRoute: LocalNewRoute,
  OnlineCreateRoute: OnlineCreateRoute,
  JoinIndexRoute: JoinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
