/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DevBoardRouteImport } from './routes/dev/board'
import { Route as DevNetworkRouteImport } from './routes/dev/network'
import { Route as LocalGameIdRouteImport } from './routes/local/$gameId'
import { Route as LocalNewRouteImport } from './routes/local/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DevBoardRoute = DevBoardRouteImport.update({
  id: '/dev/board',
  path: '/dev/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DevNetworkRoute = DevNetworkRouteImport.update({
  id: '/dev/network',
  path: '/dev/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalGameIdRoute = LocalGameIdRouteImport.update({
  id: '/local/$gameId',
  path: '/local/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalNewRoute = LocalNewRouteImport.update({
  id: '/local/new',
  path: '/local/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/dev/board': typeof DevBoardRoute
  '/dev/network': typeof DevNetworkRoute
  '/local/$gameId': typeof LocalGameIdRoute
  '/local/new': typeof LocalNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/local/$gameId'
    | '/local/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/local/$gameId'
    | '/local/new'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/dev/board'
    | '/dev/network'
    | '/local/$gameId'
    | '/local/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DevBoardRoute: typeof DevBoardRoute
  DevNetworkRoute: typeof DevNetworkRoute
  LocalGameIdRoute: typeof LocalGameIdRoute
  LocalNewRoute: typeof LocalNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/board': {
      id: '/dev/board'
      path: '/dev/board'
      fullPath: '/dev/board'
      preLoaderRoute: typeof DevBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/network': {
      id: '/dev/network'
      path: '/dev/network'
      fullPath: '/dev/network'
      preLoaderRoute: typeof DevNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$gameId': {
      id: '/local/$gameId'
      path: '/local/$gameId'
      fullPath: '/local/$gameId'
      preLoaderRoute: typeof LocalGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/new': {
      id: '/local/new'
      path: '/local/new'
      fullPath: '/local/new'
      preLoaderRoute: typeof LocalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DevBoardRoute: DevBoardRoute,
  DevNetworkRoute: DevNetworkRoute,
  LocalGameIdRoute: LocalGameIdRoute,
  LocalNewRoute: LocalNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
